production:
  solr:
    hostname: localhost
    port: 8955
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8956
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8957
    log_level: WARNING